### ISSUE TITLE
[BUG] Crash on Launch

### ISSUE THREAD

**Issue by davmopedia** [MythicApp/Mythic#93] opened 2024-06-16 14:15 UTC
**Describe the bug**
Immediate crash.

**To Reproduce**
Crash occurs immediately on launch.

**Expected behavior**
Launching the application.

**Mac (please complete the following information):**
Model: MacBook Air M1
Operating System: macOS Sonoma 14.5
App Version: 0.2.0 alpha

**Additional context**
Error log is attached
[Mythic.txt](https://github.com/user-attachments/files/15842579/Mythic.txt)

**Comment by PeeJeeDR** [comment] 2024-06-18 06:16
I'm having the same issue. I installed Kingdom Come Deliverance, after I launched it I saw the icon in my dock but the game didn't open. So I've quit Mythic but every time I want to open it now, it crashes.

**Comment by blackxfiied** [comment] 2024-06-18 13:58
Duplicate of #86

**Closed by blackxfiied** 2024-06-18 13:58 UTC
Labels: bug
