### ISSUE TITLE
[bug]: Bad CPU type in executable

### ISSUE THREAD

**Issue by Ficusbaby** [MythicApp/Mythic#159] opened 2024-10-27 23:29 UTC
### Describe the bug

When I am trying to sign into Epic Games and put the authorization code into Mythic, it says "The operation couldn't be completed. Bad CPU type in executable" I tried to redownload it but am coming back to the same issues... 

### How to reproduce

1. Try to install Mythic 
2. link your epic games account 

### Mac & App Information

MacBook Air 2019 
macOS Sonoma 

### Before submitting

- [X] I've made research efforts
- [X] I've searched for existing issues

**Comment by Ficusbaby** [comment] 2024-10-27 23:32
I did see that there was a post #36 which is the exact problem I'm having but a different model of computer to mine. 
Was wondering if someone has troubleshooted this yet?

**Comment by asxrow66** [comment] 2024-10-28 10:55
Intel CPU?

**Comment by blackxfiied** [comment] 2024-10-30 14:22
Duplicate of #36

**Closed by blackxfiied** 2024-10-30 14:22 UTC
Labels: bug
