### ISSUE TITLE
mythic game icon launcher

### ISSUE THREAD

**Issue by maxiscoolithink** [MythicApp/Mythic#71] opened 2024-05-26 00:56 UTC
![Screenshot 2024-05-25 at 7 54 57 PM](https://github.com/MythicApp/Mythic/assets/140643051/5bcd6f34-015b-4a1e-bea3-bb36c0b1b26c)

just a little icon that launches game of choice

**Comment by jeremybosma** [comment] 2024-05-26 17:54
Duplicate of #38

**Closed by jeremybosma** 2024-05-26 17:54 UTC
Labels: enhancement
