### ISSUE TITLE
"Onboarding failed to complete."

### ISSUE THREAD

**Issue by amagriz** [MythicApp/Mythic#53] opened 2024-05-20 16:12 UTC
**Describe the bug**
When launching the app, after the initial stage of logging into Epic Games and inserting the generated code, the app immediately states "Onboarding failed to complete. The operation couldn't be completed. Bad CPU type in executable.

**To Reproduce**
1. Open Mythic app
2. Generate Epic Games code and insert into app and click Next
3. See error

**Expected behavior**
To be logged into Epic Games and to continue on with the onboarding process.

**Screenshots**
<img width="1012" alt="Screenshot 2024-05-20 at 17 07 24" src="https://github.com/MythicApp/Mythic/assets/170349503/81a53eae-67bc-4706-b07f-db3bb5740525">

**Mac (please complete the following information):**
Model: MacBook Air Retina 2019
Operating System: Sonoma 14.5
App Version: 0.1.1

**Additional context**
This issue happened on 0.1 also, but previous issue logged by another user has been closed?

**Comment by AsxrowIsHim** [comment] 2024-05-20 18:45
Have you tried rolling back Mythic or reinstalling 0.1.1?

**Comment by pablopoep** [comment] 2024-05-20 18:49
if i am right u using an intell chip cuzz it is M chips only so it wont work ig

**Comment by pablopoep** [comment] 2024-05-20 18:50
it trys to install rossetta 2 but u got intel so no work
(it is not gonna be made of intel)

**Comment by AsxrowIsHim** [comment] 2024-05-20 20:20
i'm not sure if it works on intel but if you're on intel cpu, you should use **bootcamp** which is built into MacOS and has way better support for games and can run games with an anticheat

**Comment by blackxfiied** [comment] 2024-05-21 00:08
Very strange issue, it's almost as if the python script that handles Mythic's epic integration is ARM-only, which I can't replicate by running it through Rosetta.
I'll work on a fix later this week.

**Comment by amagriz** [comment] 2024-05-21 10:54
> Have you tried rolling back Mythic or reinstalling 0.1.1?

 Yeah, I tried this a couple times.

> if i am right u using an intell chip cuzz it is M chips only so it wont work ig

Oh, I didn't see anywhere that Intel chips weren't supported. Normally when this is the case, apps don't even launch on an Intel mac.

> i'm not sure if it works on intel but if you're on intel cpu, you should use **bootcamp** which is built into MacOS and has way better support for games and can run games with an anticheat

Bootcamp is unfortunately only a workaround and not a true solution to this issue. I am aware it has much better support being that it is just Windows, but I would rather not use Windows, and I'm perfectly fine with the performance hit that comes from WINE use.

> Very strange issue, it's almost as if the python script that handles Mythic's epic integration is ARM-only, which I can't replicate by running it through Rosetta. I'll work on a fix later this week.

Looking forward to a potential fix. I realised I can skip the Epic login part of the initial setup, so I am able to run the app and use all features minus the Epic integration for now.

**Comment by blackxfiied** [comment] 2024-05-21 11:23
okay, janky fix found
imma have to use pyinstaller to compile the python script for x86, that way x86 can run it natively, and ARM can use rosetta
apparently there's no way to compile for both binaries w/o a more complex solution

**Comment by billchase2** [comment] 2024-05-21 16:26
Same issue here. Is it indeed an Intel issue?

**Comment by pablopoep** [comment] 2024-05-21 16:51
yes they say it in the discord

**Comment by jeremybosma** [comment] 2024-05-31 19:45
Duplicate of #36

**Closed by jeremybosma** 2024-05-31 19:45 UTC
Labels: bug
