### ISSUE TITLE
[BUG] Error linking Epic games account

### ISSUE THREAD

**Issue by chris-gordon-io** [MythicApp/Mythic#79] opened 2024-05-31 20:07 UTC
**Describe the bug**
Unable to link Epic games account

**To Reproduce**
1. Go to accounts
2. Click on Epic games, click "here" to refresh link, copy and paste 32 digit code, hit submit
3. See error 

**Expected behavior**
Succesful linking of Epic games account

**Screenshots**

**Mac (please complete the following information):**
Model: 2017 MBP
Operating System: macOS Sonoma 14.1.1 (running via Opencore)
App Version: 0.1.1

**Additional context**
None.
<img width="949" alt="Screenshot 2024-05-31 at 20 21 32" src="https://github.com/MythicApp/Mythic/assets/6454452/e995aa80-2dc9-4fe4-adf1-fcacaec5ef2c">

**Comment by asxrow66** [comment] 2024-06-16 21:38
is this fixed for you? can help if not

**Comment by blackxfiied** [comment] 2024-06-18 03:49
not yet; this is currently expected behaviour on intel-based macs due to pyinstaller. a fix is coming soon

**Comment by blackxfiied** [comment] 2024-07-07 12:46
similar to #36, marking as duplicate.

**Closed by blackxfiied** 2024-07-07 12:46 UTC
Labels: bug
